#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
touch hull.foam

mkdir -p constant/triSurface

cp -f hull.stl constant/triSurface/

runApplication blockMesh

# z-dir refinement for free surface
runApplication topoSet -dict system/topoSetDict
runApplication refineMesh -dict system/refineMeshDict -overwrite

runApplication surfaceFeatureExtract

runApplication decomposePar

runParallel snappyHexMesh -overwrite

runParallel redistributePar -reconstruct -constant -overwrite

runApplication renumberMesh -constant -overwrite


runApplication transformPoints -origin '(2.953 0 0.399)' -yawPitchRoll '(0 0 15)' -translate '(0 0 -0.0008)' # pre roll and heave equilibrium
#------------------------------------------------------------------------------